# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
 
trigger:
  - main
  - develop
 
resources:
  repositories:
    - repository: templates
      name: unimed-pipelines
      type: git
      ref: refs/heads/main
 
variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '459a8cf0-ac1c-4bab-9c5b-155af8d891b5'
  imageRepository: 'serviceapi'
  containerRegistry: 'unimedcr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
 
stages:
  #- template: java\stages\sonar-analysis.yaml@templates
  #- template: java\stages\semantic-version.yaml@templates
  - template: java\stages\build-and-push-image.yaml@templates