name: CI
on:
  push: 
  workflow_dispatch: 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          
    
    scan:
      name: Scan da Imagem
      needs: [build]
      uses: rodolfourb/pipe-template/.github/workflows/java/stages/build-and-push.yml@main
